extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:react/recommended
    - plugin:react/jsx-runtime
ignorePatterns:
    - tmp
    - dist
    - "*.content.js"
parser: "@typescript-eslint/parser"
plugins:
    - "@typescript-eslint"
rules:
    no-shadow: off
    "@typescript-eslint/no-shadow":
        - error
    no-use-before-define: off
    "@typescript-eslint/no-use-before-define":
        - error
    react/jsx-filename-extension:
        - warn
        - extensions:
            - .tsx
    react/jsx-key:
        - off
    quotes:
        - warn
        - single
    indent:
        - warn
        - tab
    react/forbid-component-props:
        - error
        - forbid:
            - key
    "@typescript-eslint/no-explicit-any":
        - off
env:
    browser: true
settings:
    react:
        pragma: React
