MD010:
    # Include code blocks
    code_blocks: true
    # Number of spaces for each hard tab
    spaces_per_tab: 4
MD013:
    code_blocks: false
MD033:
    # Allowed elements
    allowed_elements: [img, code-preview]
MD046:
    # Block style
    style: "fenced"
