name: Run tests
on:
  workflow_call:
  push:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Fix timestamps
        run: bash .github/scripts/fix-timestamps
      #- uses: actions/cache@v4
      #  with:
      #    path: |
      #      ${{ github.workspace }}/.next/cache
      #    # Generate a new cache whenever packages or source files change.
      #    key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
      #    # If source files changed but packages didn't, rebuild from a prior cache.
      #    restore-keys: |
      #      ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          target: export
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=local,dest=/tmp/files
          tags: www.ferrybig.me:latest
        env:
          SOURCE_DATE_EPOCH: 0
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: files
          path: /tmp/files
