# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy app
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs: # push, pull_request
  tests:
    uses: ./.github/workflows/build.yml
  deploy:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: files
          path: /tmp
      - name: ssh publish
        uses: easingthemes/ssh-deploy@c711f2c3391cac2876bf4c833590077f02e4bcb8
        with:
          SSH_PRIVATE_KEY: ${{ secrets.ssh_private_key }}
          REMOTE_HOST: ${{ secrets.ssh_host }}
          REMOTE_USER: ${{ secrets.ssh_user }}
          REMOTE_PORT: 22
          SOURCE: /tmp/files
          TARGET: ${{ secrets.ssh_target }}
          ARGS: -r -l -0 -v --checksum --delete-delay
