# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy app
on:
  push:
    branches: [master]
  workflow_dispatch:
permissions:
  discussions: write
jobs: # push, pull_request
  tests:
    uses: ./.github/workflows/build.yml
  deploy:
    needs: [tests]
    runs-on: ubuntu-latest
    concurrency:
      group: Deploy
      cancel-in-progress: true
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: files
          path: tmp
      - name: ssh publish
        uses: easingthemes/ssh-deploy@01a39e33483634cbd7ac99020c55b72ca7f098fe
        with:
          SSH_PRIVATE_KEY: ${{ secrets.ssh_private_key }}
          REMOTE_HOST: cloud1.dev.ferrybig.nl
          REMOTE_USER: deploy
          REMOTE_PORT: 22
          SOURCE: tmp/
          TARGET: www.ferrybig.nl
          ARGS: -r -l -0 -v --checksum --delete-delay
      - name: Update github discussions
        uses: ferrybig/giscus-discussions-from-json@8f699fe688031a6eac6a95f768f753db3af9f792
        with:
          file: tmp/comments.json
          token: ${{ secrets.GITHUB_TOKEN }}
          categoryId: DIC_kwDOHBif1s4CdpTo
          repoOwner: ferrybig
          repoName: www.ferrybig.nl
          base: https://www.ferrybig.nl/
